import { type FC } from 'react';
import { SEO } from './common/SEO';

export const TermsOfServicePage: FC = () => (
  <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px' }}>
    <SEO title="Terms of Service | Mentor Visa" description="Read the Terms of Service for using Mentor Visa's AI-powered immigration document analysis tools." canonical="/terms-of-service" />
    
    <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '8px', color: 'var(--primary-dark)' }}>Terms of Service</h1>
    <p style={{ color: 'var(--text-muted)', marginBottom: '32px', fontSize: '0.9rem' }}>Last updated: April 8, 2026</p>

    <div style={{ lineHeight: 1.8, fontSize: '0.95rem', color: '#374151' }}>
      <p>Welcome to Mentor Visa. By accessing or using our website at <strong>mentorvisa.com</strong> ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>1. Important Legal Disclaimer</h2>
      <div style={{ background: '#FEF3C7', border: '1px solid #F59E0B', borderRadius: '8px', padding: '16px 20px', marginBottom: '20px' }}>
        <p style={{ margin: 0, fontWeight: 600, color: '#92400E' }}>⚠️ Mentor Visa is NOT a law firm and does NOT provide immigration, legal, or professional advice.</p>
        <p style={{ margin: '8px 0 0 0', color: '#92400E' }}>
          Our AI-powered tools provide <strong>informational analysis only</strong>. The results generated by our Service should not be relied upon as a substitute for professional immigration counsel. We strongly recommend consulting with a licensed Regulated Canadian Immigration Consultant (RCIC) or an immigration lawyer before making any immigration decisions.
        </p>
      </div>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>2. Description of Service</h2>
      <p>Mentor Visa provides AI-powered tools including:</p>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li><strong>Employment Letter Auditor:</strong> Analyzes employment letters against IRCC formatting and content requirements.</li>
        <li><strong>NOC Code Finder:</strong> Matches job duties to the National Occupational Classification (NOC) 2021 system.</li>
        <li><strong>CRS Calculator:</strong> Estimates Comprehensive Ranking System scores for Express Entry.</li>
        <li><strong>CEC Guide & Checklist:</strong> Informational resources for Canadian Experience Class applicants.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>3. No Guarantee of Outcomes</h2>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li>We do <strong>not</strong> guarantee the accuracy, completeness, or reliability of any analysis produced by our AI-powered tools.</li>
        <li>A "Compliant" result from our auditor does <strong>not</strong> guarantee your document will be accepted by IRCC or any immigration authority.</li>
        <li>NOC code matching is based on AI interpretation and may differ from an official IRCC assessment.</li>
        <li>CRS score calculations are estimates and may not reflect your actual score as determined by IRCC.</li>
        <li>Immigration laws, policies, and processing requirements change frequently. Our tools may not always reflect the most current requirements.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>4. User Accounts</h2>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li>You must provide accurate information when creating an account.</li>
        <li>You are responsible for maintaining the security of your account credentials.</li>
        <li>You must be at least 18 years of age to use this Service.</li>
        <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>5. Purchases and Credits</h2>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li>Certain premium features require the purchase of credits ("Passes") through Stripe.</li>
        <li>All prices are in Canadian Dollars (CAD) unless otherwise stated.</li>
        <li>Credits are non-transferable and are tied to your account.</li>
        <li>Credits do not expire.</li>
        <li>We reserve the right to change pricing at any time, though existing purchased credits will not be affected.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>6. Refund Policy</h2>
      <p>We stand behind the quality of Mentor Visa's tools and offer a <strong>3-Day Money-Back Guarantee</strong>. If you are not satisfied with your purchase, you may request a full refund within 3 days (72 hours) of the transaction by contacting us.</p>
      <p>After the 3-day guarantee period, all purchases of digital credits are considered <strong>final and non-refundable</strong>. Due to the instant-delivery nature of our digital products, we do not offer refunds after this window has closed. By completing a purchase, you acknowledge and agree to this policy.</p>
      <p>For more details, please review our full <a href="/refund-policy" style={{ color: 'var(--primary-color)' }}>Refund Policy</a>.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>7. Uploaded Content</h2>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li>You retain ownership of all documents and content you upload.</li>
        <li>By uploading content, you grant Mentor Visa a limited license to process, analyze, and store your documents solely for the purpose of providing the Service.</li>
        <li>You represent that you have the right to upload any content you submit and that it does not violate any third party's rights.</li>
        <li>Uploaded documents are sent to Google's Gemini AI for analysis. By using the Service, you consent to this processing.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>8. Limitation of Liability</h2>
      <p>To the maximum extent permitted by applicable law:</p>
      <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
        <li>Mentor Visa shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service.</li>
        <li>Our total liability for any claim arising from your use of the Service shall not exceed the amount you paid to us in the 12 months preceding the claim.</li>
        <li>We are not liable for any immigration application outcome, refusal, or delay resulting from reliance on our tools.</li>
      </ul>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>9. Indemnification</h2>
      <p>You agree to indemnify and hold harmless Mentor Visa and its operators from any claims, losses, damages, liabilities, and expenses (including legal fees) arising from your use of the Service, violation of these Terms, or violation of any third party's rights.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>10. Intellectual Property</h2>
      <p>All content, features, and functionality of the Service — including text, graphics, logos, and software — are the property of Mentor Visa and are protected by Canadian and international copyright and intellectual property laws.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>11. Governing Law</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>12. Changes to These Terms</h2>
      <p>We reserve the right to modify these Terms at any time. We will provide notice of material changes by updating the "Last updated" date. Your continued use of the Service after changes constitutes acceptance of the revised Terms.</p>

      <h2 style={{ fontSize: '1.3rem', fontWeight: 700, margin: '32px 0 12px', color: 'var(--primary-dark)' }}>13. Contact Us</h2>
      <p>If you have any questions about these Terms, please contact us:</p>
      <p style={{ marginTop: '8px' }}>
        <strong>Mentor Visa</strong><br />
        Ontario, Canada<br />
        Email: <a href="mailto:info@mentorvisa.com" style={{ color: 'var(--primary-color)' }}>info@mentorvisa.com</a>
      </p>
    </div>
  </div>
);
