import { Helmet } from 'react-helmet-async';

interface SEOProps {
  title: string;
  description: string;
  keywords?: string;
  canonical?: string;
  schema?: string;
  ogImage?: string;
  noindex?: boolean; // private/app pages: keep out of search results
}

// Routes with a dedicated OG card in public/og/ (filename = route). Generated by
// backend/gen_og_images.py — keep in sync when adding tools.
const OG_ROUTES = new Set([
  '/crs-calculator', '/find-my-noc', '/audit-employment-letter', '/track-my-application',
  '/order-gcms-notes', '/how-to-read-gcms-notes', '/gcms-notes-analyzer', '/draw-results', '/express-entry-processing-times',
  '/noc-codes', '/get-started', '/pricing',
]);

function defaultOgFor(canonical?: string): string {
  if (canonical && OG_ROUTES.has(canonical)) return `https://mentorvisa.com/og${canonical}.png`;
  if (canonical?.startsWith('/noc-codes/')) return 'https://mentorvisa.com/og/noc-codes.png';
  if (canonical?.startsWith('/draw-results/')) return 'https://mentorvisa.com/og/draw-results.png';
  return 'https://mentorvisa.com/og-image.png';
}

export const SEO = ({ title, description, keywords, canonical, schema, ogImage, noindex }: SEOProps) => {
  const imageUrl = ogImage || defaultOgFor(canonical);
  const fullUrl = canonical ? `https://mentorvisa.com${canonical}` : 'https://mentorvisa.com';

  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      {keywords && <meta name="keywords" content={keywords} />}
      {canonical && <link rel="canonical" href={fullUrl} />}
      {noindex && <meta name="robots" content="noindex, nofollow" />}

      {/* Open Graph / Facebook / LinkedIn / WhatsApp */}
      <meta property="og:type" content="website" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={fullUrl} />
      <meta property="og:image" content={imageUrl} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:site_name" content="Mentor Visa" />

      {/* Twitter Card */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={imageUrl} />

      {/* JSON-LD Structured Data */}
      {schema && (
        <script type="application/ld+json">
          {schema}
        </script>
      )}
    </Helmet>
  );
};
